# ---------------------------------
# --- APP General Configuration ---
# ---------------------------------
springdoc:
  server:
    address: localhost
    port: 8085
server:
  port: 8085

# ------------------------------------------------------------------------------------------------
# --- Database (secret-cnx-db) ---
# ------------------------------------------------------------------------------------------------
spring:
  sql:
    init:
      platform: 'org.hibernate.dialect.H2Dialect'
  datasource:
    url: jdbc:h2:mem:usersDB;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      maxLifetime: 600000
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update